# Generated by Django 4.2.7 on 2023-11-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='ga_mod_p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='gb_mod_p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='k',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='ra',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='rb',
            field=models.CharField(max_length=255),
        ),
    ]
