# Generated by Django 4.2.7 on 2023-11-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_sesion_b_alter_sesion_ga_mod_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='ga_mod_p',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='gb_mod_p',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
