# Generated by Django 4.2.7 on 2023-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_sesion_ga_mod_p_alter_sesion_gb_mod_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='tunel_establecido',
            field=models.BooleanField(default=False),
        ),
    ]
