# Generated by Django 4.2.7 on 2023-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_sesion_tunel_establecido'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='h',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
