# Generated by Django 4.2.7 on 2023-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='iv',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
